set guifont=Fura\ Code\ Retina\ Nerd\ Font\ Mono:h11
set lines=65 columns=120
set macligatures
set guioptions-=L
set guioptions-=r

" open NERDTree when gvim opens
au VimEnter * NERDTree
" open a NERDTree mirror when a new buffer window is opened
au BufWinEnter * NERDTreeMirror
" focus on the file buffer instead of NERDTree
au VimEnter * if argc() | wincmd p | endif
" close the NERDTree buffer if it is the last one standing
au BufEnter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
