" Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/nerdtree'
nnoremap <Leader>tt :NERDTreeToggle<CR>
" enable line numbers
let NERDTreeShowLineNumbers=1
" make sure relative line numbers are used
autocmd FileType nerdtree setlocal relativenumber
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1

Plugin 'rakr/vim-one'
Plugin 'sheerun/vim-polyglot'
Plugin 'scrooloose/nerdcommenter'
Plugin 'airblade/vim-gitgutter'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

Plugin 'Valloric/YouCompleteMe'
let g:ycm_autoclose_preview_window_after_insertion = 1
nnoremap <F9> :YcmCompleter FixIt<CR>

Bundle 'wellle/targets.vim'

Plugin 'derekwyatt/vim-scala'

" syntastic: Syntax checking hacks for vim
Plugin 'vim-syntastic/syntastic'
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_mode_map = { "mode": "active",
                           \ "passive_filetypes": ["scala"] }

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

call vundle#end()
filetype plugin indent on

" Colors
syntax enable           " enable syntax processing
" -- enable true color for vim
if (has("termguicolors"))
    set termguicolors
endif
" -- uncomment next line if using a transparent terminal
"highlight Normal ctermbg=NONE
" -- enable true color for tmux
if &term =~# '^screen'
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif
colorscheme one
set background=light

" Spaces and tabs
" -- global
set tabstop=4           " number of visual spaces per TAB
set softtabstop=4       " number of spaces in tab when editing
set shiftwidth=4
set expandtab           " tabs are spaces
" -- python
au BufNewFile,BufRead *.py set
    \ shiftwidth=4
    \ textwidth=79
    \ autoindent
    \ fileformat=unix
" -- java
au BufNewFile,BufRead *.java set
    \ textwidth=100
    \ autoindent
    \ fileformat=unix
    \ colorcolumn=100
" -- scala
au BufNewFile,BufRead *.scala set
    \ textwidth=100
    \ autoindent
    \ fileformat=unix
    \ colorcolumn=100

" UI config
set number relativenumber " show line numbers, relative to line
filetype indent on        " load filetype-specific indent files
set wildmenu              " visual autocomplete for command menu
set showmatch             " highlight matching [{()}]
set scrolloff=5           " lines of text around cursor
set colorcolumn=80
if &term =~ '256color'
    " Disable Background Color Erase (BCE) so that color schemes
    " work properly when Vim is used inside tmux and GNU screen.
    set t_ut=
endif

" Searching
set incsearch           " search as characters are entered
set hlsearch            " highlight matches

" Folding
set foldenable          " enable folding
set foldmethod=indent   " fold based on indent level
set foldlevel=99        " open most folds by default

" vim-airline configuration
set laststatus=2        " always show status line
let g:airline_powerline_fonts = 1 " use powerline fonts
let g:airline_theme='one'     " set theme to one dark

" Scroll the viewport faster
nnoremap <C-e> 5<C-e>
nnoremap <C-y> 5<C-y>

" window movement
nnoremap <C-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l

" Enable other stuff
filetype plugin on

" update every 1/4 of a second
set updatetime=250

