set nocompatible              " be iMproved, required
filetype off                  " required

" workaround for weird python3 bug
if has('python3')
    command! -nargs=1 Py py3 <args>
    set pythonthreedll=/usr/local/Frameworks/Python.framework/Versions/3.6/Python
    set pythonthreehome=/usr/local/Frameworks/Python.framework/Versions/3.6
else
    command! -nargs=1 Py py <args>
    set pythondll=/usr/local/Frameworks/Python.framework/Versions/2.7/Python
    set pythonhome=/usr/local/Frameworks/Python.framework/Versions/2.7
endif

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Atom colours
Plugin 'rakr/vim-one'

" airline statusline
Plugin 'vim-airline/vim-airline'

" Dev art
Plugin 'ryanoasis/vim-devicons'

" NERDTree
Plugin 'scrooloose/nerdtree'

" git integration
Plugin 'airblade/vim-gitgutter'
Plugin 'Xuyuanp/nerdtree-git-plugin'

" comment/uncomment stuff
Plugin 'tpope/vim-commentary'

" a solid language pack
Plugin 'sheerun/vim-polyglot'

" syntax checking
Plugin 'vim-syntastic/syntastic'

" ensime for Scala
Plugin 'ensime/ensime-vim'

" code completion
Plugin 'Valloric/YouCompleteMe'

" Snippets
Plugin 'SirVer/ultisnips'    " track the engine
Plugin 'honza/vim-snippets'  " get the snippets

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

set runtimepath+=~/.vimconf
so ~/.vimconf/colours.vim
so ~/.vimconf/ui.vim
so ~/.vimconf/bindings.vim
so ~/.vimconf/editor.vim
so ~/.vimconf/plugins.vim
