" Make sure vim-plug is installed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" vim-plug
call plug#begin('~/.vim/plugged')

" Plug 'edkolev/tmuxline.vim'

" Colour schemes
Plug 'dracula/vim'
Plug 'rakr/vim-one'
Plug 'ayu-theme/ayu-vim'
Plug 'lifepillar/vim-solarized8'
Plug 'arcticicestudio/nord-vim'

" airline statusline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
" Plug 'edkolev/tmuxline.vim'

" NERDTree
Plug 'scrooloose/nerdtree'

" git integration
Plug 'airblade/vim-gitgutter'
Plug 'Xuyuanp/nerdtree-git-plugin'

" comment/uncomment stuff
Plug 'tpope/vim-commentary'

" syntax checking
Plug 'vim-syntastic/syntastic'

" markdown preview
Plug 'JamshedVesuna/vim-markdown-preview'

" Snippets
Plug 'SirVer/ultisnips'    " track the engine
Plug 'honza/vim-snippets'  " get the snippets

" Scala
Plug 'derekwyatt/vim-scala'
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" fzf
Plug 'junegunn/fzf', { 'do': './install --bin' }
Plug 'junegunn/fzf.vim'

" Initialize plugin system
call plug#end()

" Personal configuration
set runtimepath+=~/.vim_config
so ~/.vim_config/colours.vim
so ~/.vim_config/ui.vim
so ~/.vim_config/bindings.vim
so ~/.vim_config/editor.vim
so ~/.vim_config/plugins.vim
so ~/.vim_config/metals.vim
