tpm:
	git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

copy:
	install -m 644 tmux.conf ~/.tmux.conf
	install -m 644 tmux-mouse-copy-linux.tmux ~/.tmux-mouse-copy-linux.tmux
	install -m 644 tmux-mouse-copy-macos.tmux ~/.tmux-mouse-copy-macos.tmux

install: tpm copy
