# set prompt and colours
PROMPT_USER="\[$(tput bold)\]\[$(tput setaf 2)\]\u\[$(tput sgr0)\]"
PROMPT_PATH="\w"

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

export PS1="${PROMPT_USER}:${PROMPT_PATH}\n\\$ "

# load bash completion
if [ -f /usr/local/share/bash-completion/bash_completion ]; then
  . /usr/local/share/bash-completion/bash_completion
fi

# load git prompt
if [ -f "/usr/local/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR="/usr/local/opt/bash-git-prompt/share"
  GIT_PROMPT_ONLY_IN_REPO=1
  source "/usr/local/opt/bash-git-prompt/share/gitprompt.sh"
fi

shopt -s autocd

# load pyenv
eval "$(pyenv init -)"
