#!/usr/bin/env bash
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

# Source all files in ~/.bash_config
BASH_CONFIG_PATH="$HOME/.bash_config"
if [ -d "$BASH_CONFIG_PATH" ]; then
    for file in "$BASH_CONFIG_PATH"/*.bash; do
        source "$file"
    done
fi
